---
# SPDX-FileCopyrightText: 2026 AntwortEinesLebens
#
# SPDX-License-Identifier: CC0-1.0
name: Check formatting of the project
on: [push]
permissions:
  contents: read
jobs:
  yamlfix:
    name: Check formatting with yamlfix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          enable-cache: true
      - name: Check YAML formatting
        run: uvx yamlfix -v --check .
  svgo:
    name: Check formatting with svgo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: '10'
          standalone: true
      - name: Check SVG formatting
        run: git ls-files -z -- '*.svg' | xargs -0 -r pnpx svgo --pretty && git diff
          --exit-code
  mdformat:
    name: Check formatting with mdformat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          enable-cache: true
      - name: Check Markdown formatting
        run: uvx mdformat --check .
